### ISSUE TITLE
Wolf just isnt there

### ISSUE THREAD

**Issue by Fr0ggy950** [akaneia/akaneia-build#12]
The custom stages and extra skins are all there and volleyball works but wolf is missing from the character select screen, plz help

**Comment by ZarkMafidag** [comment]
Hey, I had the same issue so I just deleted the ISO and re-built ensuring I used the experimental builder and it worked. You can differentiate the experimental build from the stable build from the 's' or 'f' by the version #.

**Comment by Ploaj** [comment]
Wolf was only experimental prior to v0.6
