### ISSUE TITLE
"Games" Menu not appearing on Experimental Build

### ISSUE THREAD

**Issue by cgruhler** [akaneia/akaneia-build#15]
To play volleyball you have to queue direct and select the stage, as the "Tournament Melee" button is not replaced.

**Comment by IndigoRoger** [comment]
> 
> 
> To play volleyball you have to queue direct and select the stage, as the "Tournament Melee" button is not replaced.
are you using Slippi or vanilla dolphin to play? this menu is missing in slippi as it has to edit the menu to make the online play option.

**Comment by cgruhler** [comment]
Oh, I was using slippi so I could play it online. That makes sense, thank you.
