### ISSUE TITLE
Issue creating the mod file

### ISSUE THREAD

**Issue by AngryMiner5704** [akaneia/akaneia-build#2]
it says "xdelta3: target window checksum mismatch: XD3_INVALID_INPUT"
How can I fix this?

**Comment by GabrielRRussell** [comment]
This means that the hash of your ISO does not match the hash of the file it's expecting. This is explained in the instructions file. You need a v1.02US copy of melee in the original unmodified ISO format. NKit ISOs, and GCMs, will NOT work. 

Compare the MD5 checksum of your ISO to this: "0e63d4223b01d9aba596259dc155a174", if it matches, it should work. If it does not, it won't, and will give the error message you received.

**Comment by MondayHopscotch** [comment]
Worth noting for anyone who has done it, I believe texture mods and the like will alter your ISO and cause this issue.

**Comment by AngryMiner5704** [comment]
I downloaded five different Melee ISOs and they all had the same result.

**Comment by MondayHopscotch** [comment]
@AngryMiner5704 If you're running on windows, you can confirm your own checksum by running `certutil.exe -hashfile <path to your .iso file> MD5

My ISO gives this hash: `0e63d4223b01d9aba596259dc155a174` and built correctly.

**Comment by Devost12** [comment]
Hello, i have the same issue but in my case it doesnt say xdelta3... it says xdelta is not recognized as a valid command... I used a 100% vanilla melee iso file. Whats weird is that my iso worked to build the stable version of the akaneia build but just won't work for the experimental one

**Comment by Devost12** [comment]
I also tried to check my file with MD5 and i got the exact same hash as GabrielRussel but the difference is that i have some capital letters in it:  0E63D4223B01D9ABA596259DC155A174
I anyone could explain me what i can do i would be really thankful

**Comment by AngryMiner5704** [comment]
> @AngryMiner5704 If you're running on windows, you can confirm your own checksum by running `certutil.exe -hashfile <path to your .iso file> MD5`
> 
> My ISO gives this hash: `0e63d4223b01d9aba596259dc155a174` and built correctly. Make sure you extract your iso if it's zipped.

Do I run that command through PowerShell?

**Comment by MondayHopscotch** [comment]
That looks like the path to your Akaneia builder directory, is your .iso file in that directory?

If you don't want to type your own command out, the easiest way to check your iso:

1) Navigate to the directory your ISO file is in
2) Hold Shift and Right Click, and select `Open PowerShell window here`
3) Copy-paste this command, assuming your ISO file has the same name: 
```
certutil.exe -hasfile '.\Super Smash Bros. Melee (USA) (En,Ja) (v1.02).iso' MD5
```
4) Press enter and wait for the command to show your hash (mine took a ~15 seconds to run)
5) The output should look like this (most importantly, the hash should match
```
MD5 hash of .\Super Smash Bros. Melee (USA) (En,Ja) (v1.02).iso:
0e63d4223b01d9aba596259dc155a174
CertUtil: -hashfile command completed successfully.
```

**Comment by AngryMiner5704** [comment]
It says
CertUtil: Unknown arg: -hasfile

**Comment by MondayHopscotch** [comment]
That was a typo, sorry about that. I updated my previous comment, copy-paste it once more (should be `-hashfile`)

**Comment by AngryMiner5704** [comment]
Says it can't find the file specified. Is there a download for the certutil.exe?

**Comment by MondayHopscotch** [comment]
It probably is just that your iso doesn't have the exact same name as the one in my example command. You almost certainly already have the certutil.exe based on the earlier error you got.

Just use the name of your iso file in that command and you'll know if you have the right iso or not.

**Comment by AngryMiner5704** [comment]
I got a different hash, what do I do with my tiny brain?

MD5 hash of .\Super Smash Bros. Melee (USA) (En,Ja) (Rev 2).iso:
570f5ba46604d17f2d9c4fabe4b8c34d
CertUtil: -hashfile command completed successfully.

**Comment by MondayHopscotch** [comment]
I think you'll just need to find the proper iso file. Some sites will tell you the md5 hash of the files before you download them. Google is your friend here.

**Comment by AngryMiner5704** [comment]
Can you provide a download? I can't seem to find a way to download one with that specific hash.

**Comment by AngryMiner5704** [comment]
Nevermind, I'm dumb. Fixed it!

**Comment by maxwaza1922** [comment]
Hello, i need help, You can make a version of android? I want to play akaneia But i can't find the exact md5 of melee, and drag the .ISO with the file of akaneia is impossible for me because i AM from android
