### ISSUE TITLE
Can't delete Trophy data

### ISSUE THREAD

**Issue by Daddu3** [akaneia/akaneia-build#42]
I've noticed that all Trophies had been unlocked for this game but kind of wanted to delete them for replayability's sake and also giving bit more gameplay incentive to unlock the new trophies added into the game.  However, despite trying to delete trophy data on Options, it seems to have no effect.

Is this intentional right now?

**Comment by Ploaj** [comment]
This is intentional as most trophy memory card functions are removed to allow for the trophy expansion.
