### ISSUE TITLE
Custom stages not appearing

### ISSUE THREAD

**Issue by Mafyy** [akaneia/akaneia-build#6]
I was wondering if I am missing something because I don't have the new custom stages that were created a few weeks ago. Is there some way I can get them in this build of the game? Thanks in advance!

**Comment by GabrielRRussell** [comment]
Did you actually build the ISO properly? They SHOULD show up on the Stage Select Screen with no other issue.

**Comment by Mafyy** [comment]
> Did you actually build the ISO properly? They SHOULD show up on the Stage Select Screen with no other issue.

I built the ISO from a Vanilla Melee ISO by dragging it to .bat file. Everything else works correctly but the customs stages don't show up. Just for clarification I'm talking about the custom stages like Jungle Japes, Rainbow Cruise and Onett that had been created recently, not the throwback maps that were added in this build.

**Comment by Ploaj** [comment]
Those are not part of the Akaneia build and aren't planned to be.
